// Autogenerated by Thrift Compiler (0.9.1)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package TPostStorageService

import (
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"math"
)

// (needed to ensure safety because of naive import list construction.)
var _ = math.MinInt32
var _ = thrift.ZERO
var _ = fmt.Printf

type TPostStorageService interface {
	TDataService
}

type TPostStorageServiceClient struct {
	*TDataServiceClient
}

func NewTPostStorageServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *TPostStorageServiceClient {
	return &TPostStorageServiceClient{TDataServiceClient: NewTDataServiceClientFactory(t, f)}
}

func NewTPostStorageServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *TPostStorageServiceClient {
	return &TPostStorageServiceClient{TDataServiceClient: NewTDataServiceClientProtocol(t, iprot, oprot)}
}

type TPostStorageServiceProcessor struct {
	*TDataServiceProcessor
}

func NewTPostStorageServiceProcessor(handler TPostStorageService) *TPostStorageServiceProcessor {
	self47 := &TPostStorageServiceProcessor{NewTDataServiceProcessor(handler)}
	return self47
}

// HELPER FUNCTIONS AND STRUCTURES
