/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tpoststorage_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace OpenStars { namespace Common { namespace TPostStorageService {

int _kTErrorCodeValues[] = {
  TErrorCode::EGood,
  TErrorCode::ENotFound,
  TErrorCode::EUnknown,
  TErrorCode::EDataExisted
};
const char* _kTErrorCodeNames[] = {
  "EGood",
  "ENotFound",
  "EUnknown",
  "EDataExisted"
};
const std::map<int, const char*> _TErrorCode_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kTErrorCodeValues, _kTErrorCodeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

std::ostream& operator<<(std::ostream& out, const TErrorCode::type& val) {
  std::map<int, const char*>::const_iterator it = _TErrorCode_VALUES_TO_NAMES.find(val);
  if (it != _TErrorCode_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const TErrorCode::type& val) {
  std::map<int, const char*>::const_iterator it = _TErrorCode_VALUES_TO_NAMES.find(val);
  if (it != _TErrorCode_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kTPrivacyValues[] = {
  TPrivacy::Public,
  TPrivacy::Friends,
  TPrivacy::FriendsExcept,
  TPrivacy::Onlyme,
  TPrivacy::SpecificFriends
};
const char* _kTPrivacyNames[] = {
  "Public",
  "Friends",
  "FriendsExcept",
  "Onlyme",
  "SpecificFriends"
};
const std::map<int, const char*> _TPrivacy_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(5, _kTPrivacyValues, _kTPrivacyNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

std::ostream& operator<<(std::ostream& out, const TPrivacy::type& val) {
  std::map<int, const char*>::const_iterator it = _TPrivacy_VALUES_TO_NAMES.find(val);
  if (it != _TPrivacy_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const TPrivacy::type& val) {
  std::map<int, const char*>::const_iterator it = _TPrivacy_VALUES_TO_NAMES.find(val);
  if (it != _TPrivacy_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


ActionLink::~ActionLink() noexcept {
}


void ActionLink::__set_text(const std::string& val) {
  this->text = val;
__isset.text = true;
}

void ActionLink::__set_href(const std::string& val) {
  this->href = val;
__isset.href = true;
}
std::ostream& operator<<(std::ostream& out, const ActionLink& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ActionLink::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->text);
          this->__isset.text = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->href);
          this->__isset.href = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ActionLink::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ActionLink");

  if (this->__isset.text) {
    xfer += oprot->writeFieldBegin("text", ::apache::thrift::protocol::T_STRING, 1);
    xfer += oprot->writeString(this->text);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.href) {
    xfer += oprot->writeFieldBegin("href", ::apache::thrift::protocol::T_STRING, 2);
    xfer += oprot->writeString(this->href);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ActionLink &a, ActionLink &b) {
  using ::std::swap;
  swap(a.text, b.text);
  swap(a.href, b.href);
  swap(a.__isset, b.__isset);
}

ActionLink::ActionLink(const ActionLink& other0) {
  text = other0.text;
  href = other0.href;
  __isset = other0.__isset;
}
ActionLink& ActionLink::operator=(const ActionLink& other1) {
  text = other1.text;
  href = other1.href;
  __isset = other1.__isset;
  return *this;
}
void ActionLink::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ActionLink(";
  out << "text="; (__isset.text ? (out << to_string(text)) : (out << "<null>"));
  out << ", " << "href="; (__isset.href ? (out << to_string(href)) : (out << "<null>"));
  out << ")";
}


MediaItem::~MediaItem() noexcept {
}


void MediaItem::__set_name(const std::string& val) {
  this->name = val;
}

void MediaItem::__set_mediaType(const int64_t val) {
  this->mediaType = val;
}

void MediaItem::__set_url(const std::string& val) {
  this->url = val;
}
std::ostream& operator<<(std::ostream& out, const MediaItem& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t MediaItem::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->mediaType);
          this->__isset.mediaType = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->url);
          this->__isset.url = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t MediaItem::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("MediaItem");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("mediaType", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->mediaType);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("url", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->url);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(MediaItem &a, MediaItem &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.mediaType, b.mediaType);
  swap(a.url, b.url);
  swap(a.__isset, b.__isset);
}

MediaItem::MediaItem(const MediaItem& other2) {
  name = other2.name;
  mediaType = other2.mediaType;
  url = other2.url;
  __isset = other2.__isset;
}
MediaItem& MediaItem::operator=(const MediaItem& other3) {
  name = other3.name;
  mediaType = other3.mediaType;
  url = other3.url;
  __isset = other3.__isset;
  return *this;
}
void MediaItem::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "MediaItem(";
  out << "name=" << to_string(name);
  out << ", " << "mediaType=" << to_string(mediaType);
  out << ", " << "url=" << to_string(url);
  out << ")";
}


TPostItem::~TPostItem() noexcept {
}


void TPostItem::__set_idpost(const TKey val) {
  this->idpost = val;
}

void TPostItem::__set_uid(const int64_t val) {
  this->uid = val;
}

void TPostItem::__set_content(const std::string& val) {
  this->content = val;
}

void TPostItem::__set_listMediaItems(const std::vector<MediaItem> & val) {
  this->listMediaItems = val;
__isset.listMediaItems = true;
}

void TPostItem::__set_idbackground(const std::string& val) {
  this->idbackground = val;
__isset.idbackground = true;
}

void TPostItem::__set_idfeeling(const std::string& val) {
  this->idfeeling = val;
__isset.idfeeling = true;
}

void TPostItem::__set_privacy(const int64_t val) {
  this->privacy = val;
}

void TPostItem::__set_friendsexcept(const std::vector<int64_t> & val) {
  this->friendsexcept = val;
__isset.friendsexcept = true;
}

void TPostItem::__set_specificfriends(const std::vector<int64_t> & val) {
  this->specificfriends = val;
__isset.specificfriends = true;
}

void TPostItem::__set_tagusers(const std::vector<int64_t> & val) {
  this->tagusers = val;
__isset.tagusers = true;
}

void TPostItem::__set_locationId(const std::string& val) {
  this->locationId = val;
__isset.locationId = true;
}

void TPostItem::__set_timestamps(const int64_t val) {
  this->timestamps = val;
}

void TPostItem::__set_pubkey(const std::string& val) {
  this->pubkey = val;
}

void TPostItem::__set_topubkey(const std::string& val) {
  this->topubkey = val;
__isset.topubkey = true;
}

void TPostItem::__set_touid(const int64_t val) {
  this->touid = val;
__isset.touid = true;
}

void TPostItem::__set_togroupid(const int64_t val) {
  this->togroupid = val;
__isset.togroupid = true;
}

void TPostItem::__set_actionLinks(const std::vector<ActionLink> & val) {
  this->actionLinks = val;
__isset.actionLinks = true;
}

void TPostItem::__set_mediaUrls(const std::vector<std::string> & val) {
  this->mediaUrls = val;
__isset.mediaUrls = true;
}
std::ostream& operator<<(std::ostream& out, const TPostItem& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TPostItem::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->idpost);
          this->__isset.idpost = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->uid);
          this->__isset.uid = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->content);
          this->__isset.content = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->listMediaItems.clear();
            uint32_t _size4;
            ::apache::thrift::protocol::TType _etype7;
            xfer += iprot->readListBegin(_etype7, _size4);
            this->listMediaItems.resize(_size4);
            uint32_t _i8;
            for (_i8 = 0; _i8 < _size4; ++_i8)
            {
              xfer += this->listMediaItems[_i8].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.listMediaItems = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->idbackground);
          this->__isset.idbackground = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->idfeeling);
          this->__isset.idfeeling = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->privacy);
          this->__isset.privacy = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->friendsexcept.clear();
            uint32_t _size9;
            ::apache::thrift::protocol::TType _etype12;
            xfer += iprot->readListBegin(_etype12, _size9);
            this->friendsexcept.resize(_size9);
            uint32_t _i13;
            for (_i13 = 0; _i13 < _size9; ++_i13)
            {
              xfer += iprot->readI64(this->friendsexcept[_i13]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.friendsexcept = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->specificfriends.clear();
            uint32_t _size14;
            ::apache::thrift::protocol::TType _etype17;
            xfer += iprot->readListBegin(_etype17, _size14);
            this->specificfriends.resize(_size14);
            uint32_t _i18;
            for (_i18 = 0; _i18 < _size14; ++_i18)
            {
              xfer += iprot->readI64(this->specificfriends[_i18]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.specificfriends = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->tagusers.clear();
            uint32_t _size19;
            ::apache::thrift::protocol::TType _etype22;
            xfer += iprot->readListBegin(_etype22, _size19);
            this->tagusers.resize(_size19);
            uint32_t _i23;
            for (_i23 = 0; _i23 < _size19; ++_i23)
            {
              xfer += iprot->readI64(this->tagusers[_i23]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.tagusers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 11:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->locationId);
          this->__isset.locationId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 12:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->timestamps);
          this->__isset.timestamps = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 13:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->pubkey);
          this->__isset.pubkey = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 14:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->topubkey);
          this->__isset.topubkey = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 15:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->touid);
          this->__isset.touid = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 16:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->togroupid);
          this->__isset.togroupid = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 17:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->actionLinks.clear();
            uint32_t _size24;
            ::apache::thrift::protocol::TType _etype27;
            xfer += iprot->readListBegin(_etype27, _size24);
            this->actionLinks.resize(_size24);
            uint32_t _i28;
            for (_i28 = 0; _i28 < _size24; ++_i28)
            {
              xfer += this->actionLinks[_i28].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.actionLinks = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 18:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->mediaUrls.clear();
            uint32_t _size29;
            ::apache::thrift::protocol::TType _etype32;
            xfer += iprot->readListBegin(_etype32, _size29);
            this->mediaUrls.resize(_size29);
            uint32_t _i33;
            for (_i33 = 0; _i33 < _size29; ++_i33)
            {
              xfer += iprot->readString(this->mediaUrls[_i33]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.mediaUrls = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TPostItem::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TPostItem");

  xfer += oprot->writeFieldBegin("idpost", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->idpost);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("uid", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->uid);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("content", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->content);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.listMediaItems) {
    xfer += oprot->writeFieldBegin("listMediaItems", ::apache::thrift::protocol::T_LIST, 4);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->listMediaItems.size()));
      std::vector<MediaItem> ::const_iterator _iter34;
      for (_iter34 = this->listMediaItems.begin(); _iter34 != this->listMediaItems.end(); ++_iter34)
      {
        xfer += (*_iter34).write(oprot);
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.idbackground) {
    xfer += oprot->writeFieldBegin("idbackground", ::apache::thrift::protocol::T_STRING, 5);
    xfer += oprot->writeString(this->idbackground);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.idfeeling) {
    xfer += oprot->writeFieldBegin("idfeeling", ::apache::thrift::protocol::T_STRING, 6);
    xfer += oprot->writeString(this->idfeeling);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldBegin("privacy", ::apache::thrift::protocol::T_I64, 7);
  xfer += oprot->writeI64(this->privacy);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.friendsexcept) {
    xfer += oprot->writeFieldBegin("friendsexcept", ::apache::thrift::protocol::T_LIST, 8);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>(this->friendsexcept.size()));
      std::vector<int64_t> ::const_iterator _iter35;
      for (_iter35 = this->friendsexcept.begin(); _iter35 != this->friendsexcept.end(); ++_iter35)
      {
        xfer += oprot->writeI64((*_iter35));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.specificfriends) {
    xfer += oprot->writeFieldBegin("specificfriends", ::apache::thrift::protocol::T_LIST, 9);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>(this->specificfriends.size()));
      std::vector<int64_t> ::const_iterator _iter36;
      for (_iter36 = this->specificfriends.begin(); _iter36 != this->specificfriends.end(); ++_iter36)
      {
        xfer += oprot->writeI64((*_iter36));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.tagusers) {
    xfer += oprot->writeFieldBegin("tagusers", ::apache::thrift::protocol::T_LIST, 10);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I64, static_cast<uint32_t>(this->tagusers.size()));
      std::vector<int64_t> ::const_iterator _iter37;
      for (_iter37 = this->tagusers.begin(); _iter37 != this->tagusers.end(); ++_iter37)
      {
        xfer += oprot->writeI64((*_iter37));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.locationId) {
    xfer += oprot->writeFieldBegin("locationId", ::apache::thrift::protocol::T_STRING, 11);
    xfer += oprot->writeString(this->locationId);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldBegin("timestamps", ::apache::thrift::protocol::T_I64, 12);
  xfer += oprot->writeI64(this->timestamps);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pubkey", ::apache::thrift::protocol::T_STRING, 13);
  xfer += oprot->writeString(this->pubkey);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.topubkey) {
    xfer += oprot->writeFieldBegin("topubkey", ::apache::thrift::protocol::T_STRING, 14);
    xfer += oprot->writeString(this->topubkey);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.touid) {
    xfer += oprot->writeFieldBegin("touid", ::apache::thrift::protocol::T_I64, 15);
    xfer += oprot->writeI64(this->touid);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.togroupid) {
    xfer += oprot->writeFieldBegin("togroupid", ::apache::thrift::protocol::T_I64, 16);
    xfer += oprot->writeI64(this->togroupid);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.actionLinks) {
    xfer += oprot->writeFieldBegin("actionLinks", ::apache::thrift::protocol::T_LIST, 17);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->actionLinks.size()));
      std::vector<ActionLink> ::const_iterator _iter38;
      for (_iter38 = this->actionLinks.begin(); _iter38 != this->actionLinks.end(); ++_iter38)
      {
        xfer += (*_iter38).write(oprot);
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.mediaUrls) {
    xfer += oprot->writeFieldBegin("mediaUrls", ::apache::thrift::protocol::T_LIST, 18);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->mediaUrls.size()));
      std::vector<std::string> ::const_iterator _iter39;
      for (_iter39 = this->mediaUrls.begin(); _iter39 != this->mediaUrls.end(); ++_iter39)
      {
        xfer += oprot->writeString((*_iter39));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TPostItem &a, TPostItem &b) {
  using ::std::swap;
  swap(a.idpost, b.idpost);
  swap(a.uid, b.uid);
  swap(a.content, b.content);
  swap(a.listMediaItems, b.listMediaItems);
  swap(a.idbackground, b.idbackground);
  swap(a.idfeeling, b.idfeeling);
  swap(a.privacy, b.privacy);
  swap(a.friendsexcept, b.friendsexcept);
  swap(a.specificfriends, b.specificfriends);
  swap(a.tagusers, b.tagusers);
  swap(a.locationId, b.locationId);
  swap(a.timestamps, b.timestamps);
  swap(a.pubkey, b.pubkey);
  swap(a.topubkey, b.topubkey);
  swap(a.touid, b.touid);
  swap(a.togroupid, b.togroupid);
  swap(a.actionLinks, b.actionLinks);
  swap(a.mediaUrls, b.mediaUrls);
  swap(a.__isset, b.__isset);
}

TPostItem::TPostItem(const TPostItem& other40) {
  idpost = other40.idpost;
  uid = other40.uid;
  content = other40.content;
  listMediaItems = other40.listMediaItems;
  idbackground = other40.idbackground;
  idfeeling = other40.idfeeling;
  privacy = other40.privacy;
  friendsexcept = other40.friendsexcept;
  specificfriends = other40.specificfriends;
  tagusers = other40.tagusers;
  locationId = other40.locationId;
  timestamps = other40.timestamps;
  pubkey = other40.pubkey;
  topubkey = other40.topubkey;
  touid = other40.touid;
  togroupid = other40.togroupid;
  actionLinks = other40.actionLinks;
  mediaUrls = other40.mediaUrls;
  __isset = other40.__isset;
}
TPostItem& TPostItem::operator=(const TPostItem& other41) {
  idpost = other41.idpost;
  uid = other41.uid;
  content = other41.content;
  listMediaItems = other41.listMediaItems;
  idbackground = other41.idbackground;
  idfeeling = other41.idfeeling;
  privacy = other41.privacy;
  friendsexcept = other41.friendsexcept;
  specificfriends = other41.specificfriends;
  tagusers = other41.tagusers;
  locationId = other41.locationId;
  timestamps = other41.timestamps;
  pubkey = other41.pubkey;
  topubkey = other41.topubkey;
  touid = other41.touid;
  togroupid = other41.togroupid;
  actionLinks = other41.actionLinks;
  mediaUrls = other41.mediaUrls;
  __isset = other41.__isset;
  return *this;
}
void TPostItem::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TPostItem(";
  out << "idpost=" << to_string(idpost);
  out << ", " << "uid=" << to_string(uid);
  out << ", " << "content=" << to_string(content);
  out << ", " << "listMediaItems="; (__isset.listMediaItems ? (out << to_string(listMediaItems)) : (out << "<null>"));
  out << ", " << "idbackground="; (__isset.idbackground ? (out << to_string(idbackground)) : (out << "<null>"));
  out << ", " << "idfeeling="; (__isset.idfeeling ? (out << to_string(idfeeling)) : (out << "<null>"));
  out << ", " << "privacy=" << to_string(privacy);
  out << ", " << "friendsexcept="; (__isset.friendsexcept ? (out << to_string(friendsexcept)) : (out << "<null>"));
  out << ", " << "specificfriends="; (__isset.specificfriends ? (out << to_string(specificfriends)) : (out << "<null>"));
  out << ", " << "tagusers="; (__isset.tagusers ? (out << to_string(tagusers)) : (out << "<null>"));
  out << ", " << "locationId="; (__isset.locationId ? (out << to_string(locationId)) : (out << "<null>"));
  out << ", " << "timestamps=" << to_string(timestamps);
  out << ", " << "pubkey=" << to_string(pubkey);
  out << ", " << "topubkey="; (__isset.topubkey ? (out << to_string(topubkey)) : (out << "<null>"));
  out << ", " << "touid="; (__isset.touid ? (out << to_string(touid)) : (out << "<null>"));
  out << ", " << "togroupid="; (__isset.togroupid ? (out << to_string(togroupid)) : (out << "<null>"));
  out << ", " << "actionLinks="; (__isset.actionLinks ? (out << to_string(actionLinks)) : (out << "<null>"));
  out << ", " << "mediaUrls="; (__isset.mediaUrls ? (out << to_string(mediaUrls)) : (out << "<null>"));
  out << ")";
}


TDataResult::~TDataResult() noexcept {
}


void TDataResult::__set_errorCode(const TErrorCode::type val) {
  this->errorCode = val;
}

void TDataResult::__set_data(const TPostItem& val) {
  this->data = val;
__isset.data = true;
}
std::ostream& operator<<(std::ostream& out, const TDataResult& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TDataResult::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast42;
          xfer += iprot->readI32(ecast42);
          this->errorCode = (TErrorCode::type)ecast42;
          this->__isset.errorCode = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->data.read(iprot);
          this->__isset.data = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TDataResult::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TDataResult");

  xfer += oprot->writeFieldBegin("errorCode", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32((int32_t)this->errorCode);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.data) {
    xfer += oprot->writeFieldBegin("data", ::apache::thrift::protocol::T_STRUCT, 2);
    xfer += this->data.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TDataResult &a, TDataResult &b) {
  using ::std::swap;
  swap(a.errorCode, b.errorCode);
  swap(a.data, b.data);
  swap(a.__isset, b.__isset);
}

TDataResult::TDataResult(const TDataResult& other43) {
  errorCode = other43.errorCode;
  data = other43.data;
  __isset = other43.__isset;
}
TDataResult& TDataResult::operator=(const TDataResult& other44) {
  errorCode = other44.errorCode;
  data = other44.data;
  __isset = other44.__isset;
  return *this;
}
void TDataResult::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TDataResult(";
  out << "errorCode=" << to_string(errorCode);
  out << ", " << "data="; (__isset.data ? (out << to_string(data)) : (out << "<null>"));
  out << ")";
}


TListDataResult::~TListDataResult() noexcept {
}


void TListDataResult::__set_errorCode(const TErrorCode::type val) {
  this->errorCode = val;
}

void TListDataResult::__set_listDatas(const std::vector<TPostItem> & val) {
  this->listDatas = val;
}
std::ostream& operator<<(std::ostream& out, const TListDataResult& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TListDataResult::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast45;
          xfer += iprot->readI32(ecast45);
          this->errorCode = (TErrorCode::type)ecast45;
          this->__isset.errorCode = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->listDatas.clear();
            uint32_t _size46;
            ::apache::thrift::protocol::TType _etype49;
            xfer += iprot->readListBegin(_etype49, _size46);
            this->listDatas.resize(_size46);
            uint32_t _i50;
            for (_i50 = 0; _i50 < _size46; ++_i50)
            {
              xfer += this->listDatas[_i50].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.listDatas = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TListDataResult::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TListDataResult");

  xfer += oprot->writeFieldBegin("errorCode", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32((int32_t)this->errorCode);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("listDatas", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->listDatas.size()));
    std::vector<TPostItem> ::const_iterator _iter51;
    for (_iter51 = this->listDatas.begin(); _iter51 != this->listDatas.end(); ++_iter51)
    {
      xfer += (*_iter51).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TListDataResult &a, TListDataResult &b) {
  using ::std::swap;
  swap(a.errorCode, b.errorCode);
  swap(a.listDatas, b.listDatas);
  swap(a.__isset, b.__isset);
}

TListDataResult::TListDataResult(const TListDataResult& other52) {
  errorCode = other52.errorCode;
  listDatas = other52.listDatas;
  __isset = other52.__isset;
}
TListDataResult& TListDataResult::operator=(const TListDataResult& other53) {
  errorCode = other53.errorCode;
  listDatas = other53.listDatas;
  __isset = other53.__isset;
  return *this;
}
void TListDataResult::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TListDataResult(";
  out << "errorCode=" << to_string(errorCode);
  out << ", " << "listDatas=" << to_string(listDatas);
  out << ")";
}

}}} // namespace
